=== compomics/pride-asa-pipeline/trunk/src/main/resources/modifications.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="modifications">
        <xs:complexType>      
            <xs:sequence>      
                <xs:element ref="modification" minOccurs="1" maxOccurs="unbounded"/> 
            </xs:sequence>          
        </xs:complexType>
    </xs:element>
    <xs:element name="modification">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="monoIsotopicMassShift" type="xs:string"/>
                <xs:element name="averageMassShift" type="xs:string"/>
                <xs:element ref="location"/>                
                <xs:element name="affectedAminoAcids">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="affectedAminoAcid" minOccurs="1" maxOccurs="unbounded"/> 
                        </xs:sequence>                               
                    </xs:complexType>
                </xs:element>
                <xs:element name="accession" type="xs:string"/>
                <xs:element name="accessionValue" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="location">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="any"/>
                <xs:enumeration value="N-terminus"/>
                <xs:enumeration value="C-terminus"/>
            </xs:restriction>    
        </xs:simpleType>    
    </xs:element>     
    <xs:element name="affectedAminoAcid">
        <xs:simpleType>
            <xs:restriction base="xs:string">                                
                <xs:enumeration value="*"/>
                <xs:enumeration value="A"/>
                <xs:enumeration value="R"/>
                <xs:enumeration value="N"/>
                <xs:enumeration value="D"/>
                <xs:enumeration value="C"/>
                <xs:enumeration value="E"/>
                <xs:enumeration value="Q"/>
                <xs:enumeration value="G"/>
                <xs:enumeration value="H"/>
                <xs:enumeration value="I"/>
                <xs:enumeration value="J"/>
                <xs:enumeration value="K"/>
                <xs:enumeration value="L"/>
                <xs:enumeration value="M"/>
                <xs:enumeration value="F"/>
                <xs:enumeration value="P"/>
                <xs:enumeration value="S"/>
                <xs:enumeration value="T"/>
                <xs:enumeration value="U"/>
                <xs:enumeration value="W"/>
                <xs:enumeration value="Y"/>
                <xs:enumeration value="V"/>                
                <xs:enumeration value="O"/>                
                <xs:enumeration value="B"/>                
                <xs:enumeration value="Z"/>                
                <xs:enumeration value="X"/>                
            </xs:restriction>    
        </xs:simpleType> 
    </xs:element>              
</xs:schema>

=== compomics/pride-asa-pipeline/trunk/pride-asa-pipeline-core/src/test/resources/conflicting_pride_asap_modifications_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<modifications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="modifications.xsd">
    <modification>
        <name>Acetylation</name>
        <monoIsotopicMassShift>82.01056</monoIsotopicMassShift>
        <averageMassShift>82.0367</averageMassShift>
        <location>any</location>
        <affectedAminoAcids>
            <affectedAminoAcid>K</affectedAminoAcid>
        </affectedAminoAcids>
        <accession>MOD:00064</accession>
        <accessionValue>N6-acetyl-L-lysine</accessionValue>
    </modification>
    <modification>
        <name>Terminal Acetylation</name>
        <!-- <monoIsotopicMassShift>42.010565</monoIsotopicMassShift> --> <!-- mass different at last comma. program currently can't cope with modifications which have exactly same mass -->
        <monoIsotopicMassShift>82.01057</monoIsotopicMassShift>
        <averageMassShift>82.0368</averageMassShift>
        <location>any</location>
        <affectedAminoAcids>
            <!--<affectedAminoAcid>*</affectedAminoAcid>--> <!-- * is wildcard for all amino acids -->
            <affectedAminoAcid>A</affectedAminoAcid>
            <affectedAminoAcid>M</affectedAminoAcid>
            <affectedAminoAcid>S</affectedAminoAcid>
            <affectedAminoAcid>K</affectedAminoAcid>
        </affectedAminoAcids>
        <accession>MOD:00408</accession>
        <accessionValue>N-acetylated residue</accessionValue>
    </modification>
    <modification>
        <name>Carboxyamidomethylation</name>
        <monoIsotopicMassShift>57.02146</monoIsotopicMassShift>
        <averageMassShift>57.0513</averageMassShift>
        <location>any</location>
        <affectedAminoAcids>
            <affectedAminoAcid>Y</affectedAminoAcid>
        </affectedAminoAcids>
        <accession>MOD:01060</accession>
        <accessionValue>Carboxyamidomethyl Cystenyl</accessionValue>
    </modification>
    <modification>
        <name>Oxidation</name>
        <monoIsotopicMassShift>75.994915</monoIsotopicMassShift>
        <averageMassShift>75.9994</averageMassShift>
        <location>C-terminus</location>
        <affectedAminoAcids>
            <affectedAminoAcid>A</affectedAminoAcid>
        </affectedAminoAcids>
        <accession>MOD:00719</accession>
        <accessionValue>oxidation to L-methionine sulfoxide</accessionValue>
    </modification>
    <modification>
        <name>Terminal Oxidation</name>
        <monoIsotopicMassShift>75.994915</monoIsotopicMassShift>
        <averageMassShift>75.9994</averageMassShift>
        <location>C-terminus</location>
        <affectedAminoAcids>
            <affectedAminoAcid>A</affectedAminoAcid>
        </affectedAminoAcids>
        <accession>MOD:00719</accession>
        <accessionValue>oxidation to L-methionine sulfoxide</accessionValue>
    </modification>
</modifications>

=== compomics/pride-asa-pipeline/trunk/src/main/resources/resources/modifications_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<modifications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="modifications.xsd">    
	<modification>
        <name>iTRAQ4plex114</name>
        <monoIsotopicMassShift>144.105919</monoIsotopicMassShift>
        <averageMassShift>144.105919</averageMassShift>
        <location>any</location>
        <affectedAminoAcids>
            <affectedAminoAcid>K</affectedAminoAcid>
        </affectedAminoAcids>
        <accession>MOD:01485</accession>
        <accessionValue>iTRAQ4plex-114 reporter+balance reagent acylated residue</accessionValue>
    </modification>
    <modification>
        <name>N_term_iTRAQ4plex114oo</name>
        <monoIsotopicMassShift>144.105919</monoIsotopicMassShift>
        <averageMassShift>144.105919</averageMassShift>
        <location>N-terminus</location>
        <affectedAminoAcids>
            <affectedAminoAcid>G</affectedAminoAcid>
            <affectedAminoAcid>L</affectedAminoAcid>
        </affectedAminoAcids>
        <accession>MOD:01485lll</accession>
        <accessionValue>N_term_iTRAQ4plex-114 reporter+balance reagent acylated residueiojijij</accessionValue>
    </modification>
</modifications>
